Fix: Use publish_date parameter instead of undefined publish_date_utc
Bug: Referenced publish_date_utc inside create_kit_broadcast function
but that variable doesn't exist there - it's passed as 'publish_date' parameter.

Error: name 'publish_date_utc' is not defined